// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdinzuwwjudpvsvaouln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkaW56dXd3anVkcHZzdmFvdWxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzQ0ODUsImV4cCI6MjA2OTkxMDQ4NX0.qs_eRqQ6BmEsC1yutUX6gxd5lW197qErmZMujkY5a_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});